### ISSUE TITLE
Feature Request - Allow flag to force cycle instance even if launch config hasn't change

### ISSUE THREAD

**Issue by CAR6807** [keikoproj/upgrade-manager#90]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request
**What happened**:

Big Fan of the project, but would like to submit a feature request.

I noticed in previous versions the instances would cycle regardless whether of the underlying launch config has changed or not. In the recent releases, this behavior was fixed to only cycle instances when the launch config has changed. 
In most cases we use upgrade manager to cycle instances every 30 days for new AMI releases and intended behavior works just fine. But in other cases, where we want to cycle nodes in our cluster to pickup non-launch config changes (DNS, agent refreshes, etc) or just cycle the nodes to refresh the environment, it would be nice have a "force-cycle" parameter in the CRD to tell Upgrade Manager to cycle instances regardless if there is a launch config change or not. 
Let me know what you think.

Thanks.

**Comment by shrinandj** [comment]
Thanks for filing this.

The `force` flag could be implemented such that the launch-config is ignored when terminating instances. Meanwhile, you could use [https://github.com/keikoproj/governor 
](https://github.com/keikoproj/governor ) as a Cronjob for reaping old instances.

See these deployment instructions https://github.com/keikoproj/governor/blob/master/examples/node-reaper.yaml. You might only need
```
            args:
            - governor
            - reap
            - node
            - --dry-run=false
            # Old nodes are reapable
            - --reap-old
            # Nodes older than 30 days are considered age-reapable
            - --reap-old-threshold-minutes=43200
            # Wait 1hr after each old node termination
            - --reap-old-throttle=3600
            # Kill a maximum of 1 nodes per run considering throttle wait times
            - --max-kill-nodes=1
```

**Comment by CAR6807** [comment]
Thanks for the information, will look into governor. I guess in our use case, we frequently cycle nodes for changes outside of launch config changes, and would like to leverage our existing automation (dynamically generating CRDs) around upgrade manager. Thanks for the help

**Comment by shrinandj** [comment]
## Requirements
- Each CR should include a flag that indicates whether the restacking of the ASG should happen regardless of whether the launch config/template has changed or not.
- If the flag is set, the restack should happen gracefully: run the pre-drain scripts, drain the node, post-drain scripts, wait, terminate the instance, etc.

## Design
- Introduce a new flag in the CRD called `forceRefresh`
- Default value of the flag should be `false`
- The `UpdateInstance` method of the `RollingUpgradeReconciler` object internally checks whether the launch configs or templates match using the function `requiresRefresh`. This function currently takes the instance object and LaunchDefinition as arguments. This function could be made a method of the `RollingUpgradeReconciler` object.
- Pass the `rollingupgrade` object to it as a parameter (`ruObj *upgrademgrv1alpha1.RollingUpgrade`)
- Use the `ruObj` to check whether the `forecRefresh` flag is set. If yes, simply return `true` from the method. Otherwise, let it check the launch-config, templates, etc.
- Some log messages that need to be updated accordingly.
